spring.application.name=AuthenticationService
# Database connection settings
spring.datasource.url=jdbc:mysql://localhost:3306/auth_service
spring.datasource.username=root
spring.datasource.password=Summer@5
# Spring JPA settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true